Repository What-s-Popping/popping_BE, pull requests merged in 2024-11, with the labels that each got.

#2 feat: module setting과 jwt를 활용한 security setting
  poppingcore/boot/batch/build.gradle
  poppingcore/boot/batch/src/main/java/com/popping/BatchApplication.java
  poppingcore/boot/external-api/build.gradle
  poppingcore/boot/external-api/src/main/java/com/popping/ExternalApiApplication.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/aws/controller/AwsLbController.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/config/jwt/JwtAuthenticationFilter.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/config/jwt/JwtProperties.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/config/jwt/TokenProvider.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/config/security/SecurityConfig.java
  poppingcore/boot/external-api/src/main/resources/application.yml
  poppingcore/build.gradle
  poppingcore/data/build.gradle
  poppingcore/data/src/main/java/com/popping/data/member/role/Role.java
  poppingcore/data/src/main/resources/application.yml
  poppingcore/settings.gradle
  poppingcore/src/main/java/com/popping/poppingcore/PoppingcoreApplication.java
  poppingcore/src/main/resources/application.yml
  poppingcore/src/test/java/com/popping/poppingcore/PoppingcoreApplicationTests.java
Labels: feat, 호왕

#4 feat: 로그인과 회원가입 관련 API 개발
  poppingcore/boot/external-api/build.gradle
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/controller/AuthMemberController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/controller/SmsController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/controller/TokenController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/dto/AuthMemberDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/dto/AuthSmsDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/dto/TokenDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SignInService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SignUpService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SmsVerifyService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/TokenService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/img/service/ImgSaveService.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/advice/ValidExceptionHandler.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/config/jwt/JwtAuthenticationFilter.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/config/jwt/TokenProvider.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/config/security/SecurityConfig.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/exception/SignInRequiredException.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/exceptionmessage/ExceptionMessage.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/responseform/ResponseForm.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/responseform/ResponseStatus.java
  poppingcore/boot/external-api/src/main/resources/application.yml
  poppingcore/build.gradle
  poppingcore/cloud/build.gradle
  poppingcore/cloud/src/main/java/com/popping/client/aws/s3/S3Service.java
  poppingcore/cloud/src/main/java/com/popping/config/aws/s3/S3Config.java
  poppingcore/cloud/src/main/resources/application-cloud.yml
  poppingcore/data/build.gradle
  poppingcore/data/src/main/java/com/popping/data/member/data/member/entity/Member.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/entity/PolicyTerm.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/entity/ostype/OsType.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/entity/role/Role.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/entity/signupplatform/SignUpPlatform.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/repository/MemberRepository.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/repository/PolicyTermRepository.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/service/MemberService.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/service/PolicyTermService.java
  poppingcore/data/src/main/java/com/popping/global/exceptionmessage/ExceptionMessage.java
  poppingcore/data/src/main/resources/application-data.yml
  poppingcore/settings.gradle
Labels: feat, 호왕

#6 pop upload
  poppingcore/boot/external-api/src/main/java/com/popping/ExternalApiApplication.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SignUpService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/friend/controller/FriendController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/friend/dto/FindFriendDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/friend/service/FindFriendService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/img/controller/ImgController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/img/dto/PostImgDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/img/service/ImgSaveService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/controller/MemberController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/dto/PopcornDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/dto/PrivateProfile.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/service/PopcornService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/service/PrivateProfileService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/controller/PopController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/dto/ChipDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/dto/PopDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/service/SavePopService.java
  poppingcore/cloud/src/main/java/com/popping/client/aws/s3/S3Service.java
  poppingcore/data/build.gradle
  poppingcore/data/src/main/java/com/popping/data/friendgroup/entity/CommonGroup.java
  poppingcore/data/src/main/java/com/popping/data/friendgroup/entity/FriendGroup.java
  poppingcore/data/src/main/java/com/popping/data/friendgroup/entity/FriendGroupMember.java
  poppingcore/data/src/main/java/com/popping/data/friendgroup/repository/FriendGroupMemberRepository.java
  poppingcore/data/src/main/java/com/popping/data/friendgroup/repository/FriendGroupRepository.java
  poppingcore/data/src/main/java/com/popping/data/friendgroup/service/FriendGroupMemberService.java
  poppingcore/data/src/main/java/com/popping/data/friendgroup/service/FriendGroupService.java
  poppingcore/data/src/main/java/com/popping/data/img/entity/Img.java
  poppingcore/data/src/main/java/com/popping/data/img/repository/ImgRepository.java
  poppingcore/data/src/main/java/com/popping/data/img/service/ImgService.java
  poppingcore/data/src/main/java/com/popping/data/member/data/feed/entity/Feed.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/entity/Member.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/repository/MemberRepository.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/service/MemberService.java
  poppingcore/data/src/main/java/com/popping/data/post/chip/Chip.java
  poppingcore/data/src/main/java/com/popping/data/post/chip/ColorChip.java
  poppingcore/data/src/main/java/com/popping/data/post/entity/Pop.java
  poppingcore/data/src/main/java/com/popping/data/post/entity/SharedGroup.java
  poppingcore/data/src/main/java/com/popping/data/post/entity/SharedGroupMember.java
  poppingcore/data/src/main/java/com/popping/data/post/repository/PostRepository.java
  poppingcore/data/src/main/java/com/popping/data/post/repository/SharedGroupMemberRepository.java
  poppingcore/data/src/main/java/com/popping/data/post/repository/SharedGroupRepository.java
  poppingcore/data/src/main/java/com/popping/data/post/service/PopService.java
  poppingcore/data/src/main/java/com/popping/data/post/service/SharedGroupMemberService.java
  poppingcore/data/src/main/java/com/popping/data/post/service/SharedGroupService.java
  poppingcore/data/src/main/java/com/popping/global/entity/BaseEntity.java
Labels: feat, 정우

#8 feat<Frame> : 현재 띄울 프레임 정보 조회 API 구현
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/dto/AuthMemberDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SignInService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SignUpService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SmsVerifyService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/TokenService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/frame/controller/FrameController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/frame/dto/FrameDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/frame/service/FindFrameService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/service/PopcornService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/service/SavePopService.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/config/jwt/TokenProvider.java
  poppingcore/data/src/main/java/com/popping/data/feed/entity/Feed.java
  poppingcore/data/src/main/java/com/popping/data/frame/entity/Frame.java
  poppingcore/data/src/main/java/com/popping/data/frame/repository/FrameRepository.java
  poppingcore/data/src/main/java/com/popping/data/frame/service/FrameService.java
  poppingcore/data/src/main/java/com/popping/data/friendgroup/entity/FriendGroup.java
  poppingcore/data/src/main/java/com/popping/data/friendgroup/entity/FriendGroupMember.java
  poppingcore/data/src/main/java/com/popping/data/member/data/member/entity/ostype/OsType.java
  poppingcore/data/src/main/java/com/popping/data/member/entity/Member.java
  poppingcore/data/src/main/java/com/popping/data/member/entity/PolicyTerm.java
  poppingcore/data/src/main/java/com/popping/data/member/entity/ostype/OsType.java
  poppingcore/data/src/main/java/com/popping/data/member/entity/role/Role.java
  poppingcore/data/src/main/java/com/popping/data/member/entity/signupplatform/SignUpPlatform.java
  poppingcore/data/src/main/java/com/popping/data/member/repository/MemberRepository.java
  poppingcore/data/src/main/java/com/popping/data/member/repository/PolicyTermRepository.java
  poppingcore/data/src/main/java/com/popping/data/member/service/MemberService.java
  poppingcore/data/src/main/java/com/popping/data/member/service/PolicyTermService.java
  poppingcore/data/src/main/java/com/popping/data/post/entity/Pop.java
  poppingcore/data/src/main/java/com/popping/data/post/entity/SharedGroupMember.java
  poppingcore/data/src/main/java/com/popping/global/exceptionmessage/ExceptionMessage.java
Labels: feat, 호왕

#10 결제와 활동상태 제외하고 구현 끝
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/dto/MemberInfoDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/dto/PopDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/dto/ProfileDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/service/MyPopService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/service/ProfileService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/popcorn/controller/PopcornController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/popcorn/service/ReceiptValidService.java
  poppingcore/cloud/src/main/java/com/popping/client/aws/s3/S3ImgPathPrefix.java
  poppingcore/data/src/main/java/com/popping/data/post/repository/PopRepository.java
Labels: feat, 정우

#11 feat/my-page
  poppingcore/boot/external-api/build.gradle
  poppingcore/boot/external-api/src/main/java/com/popping/domain/admin/controller/AdminController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/admin/dto/AdminLoginDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/dto/AuthMemberDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SignUpService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/img/service/ImgSaveService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/controller/MemberController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/dto/MemberInfoDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/dto/PopDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/dto/ProfileDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/service/MyPopService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/service/ProfileService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/popcorn/controller/PopcornController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/popcorn/service/ReceiptValidService.java
  poppingcore/boot/external-api/src/main/java/com/popping/global/config/security/SecurityConfig.java
  poppingcore/boot/external-api/src/main/resources/templates/home.html
  poppingcore/boot/external-api/src/main/resources/templates/index.html
  poppingcore/cloud/src/main/java/com/popping/client/aws/s3/S3ImgPathPrefix.java
  poppingcore/cloud/src/main/java/com/popping/client/aws/s3/S3Service.java
  poppingcore/data/src/main/java/com/popping/data/member/entity/Member.java
  poppingcore/data/src/main/java/com/popping/data/popcorn/PopcornService.java
  poppingcore/data/src/main/java/com/popping/data/popcorn/entity/PopcornPayment.java
  poppingcore/data/src/main/java/com/popping/data/popcorn/entity/popcorntype/PopcornType.java
  poppingcore/data/src/main/java/com/popping/data/popcorn/repository/PopcornRepository.java
  poppingcore/data/src/main/java/com/popping/data/post/repository/PopRepository.java
  poppingcore/data/src/main/java/com/popping/data/post/service/PopService.java
Labels: feat, 정우

#14 남은 무료 익명 횟수 조회 로직 변경
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/controller/MemberController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/member/service/PrivateProfileService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/controller/PopController.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/dto/PopDto.java
  poppingcore/data/src/main/java/com/popping/data/post/repository/PopRepository.java
  poppingcore/data/src/main/java/com/popping/data/post/service/PopService.java
Labels: refactor, 정우
