Repository What-s-Popping/popping_BE, pull requests merged in 2025-01, with the labels that each got.

#20 refactor: signIn API 반환 데이터에 사용자 정보 추가
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/dto/AuthMemberDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SignInService.java
  poppingcore/data/src/main/java/com/popping/data/pop/chip/ColorChip.java
  poppingcore/data/src/main/java/com/popping/data/pop/repository/PopRepository.java
  poppingcore/data/src/main/java/com/popping/data/pop/repository/RePopRepository.java
Labels: refactor, 호왕

#23 fix: @RequestParam이 아닌 @ModelAttribute로 받도록 수정
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/controller/AuthMemberController.java
Labels: fix, 호왕

#27 fix: 누락된 사용자 친구 그룹 설정 로직 추가
  poppingcore/boot/external-api/src/main/java/com/popping/domain/auth/service/SignUpService.java
  poppingcore/data/src/main/java/com/popping/data/friendgroup/service/FriendGroupService.java
  poppingcore/data/src/main/java/com/popping/data/member/repository/MemberRepository.java
  poppingcore/data/src/main/java/com/popping/data/member/service/MemberService.java
Labels: fix, 호왕

#28 feat/my-pop-active-user
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/dto/PopActionMemberDto.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/service/FindPopService.java
  poppingcore/boot/external-api/src/main/java/com/popping/domain/pop/service/FindRePopService.java
  poppingcore/data/src/main/java/com/popping/data/pop/repository/PopActionStateRepository.java
  poppingcore/data/src/main/java/com/popping/data/pop/repository/RePopActionStateRepository.java
Labels: fix, 정우
